<center><h2><u>Name </u>: Muhammad Fahad Siddiqui</h2></center>
<center><h2><u>Roll # </u>: PIAIC131745</h2></center>

# Apply Numpy 20 Universal functions

In [1]:
#importing numpy 

import numpy as np
print(np)


<module 'numpy' from '/home/fadflex/anaconda3/lib/python3.9/site-packages/numpy/__init__.py'>


In [27]:
#creating numpy arrays

a = np.arange(3*3).reshape(3,3)
display(a)

b = np.arange(3*3).reshape(3,3)**2
display(b)

c = np.array([-1, -2, 3, 4])
display(c)

d = np.array([1, 4, 9, 16])
display(d)

e = np.array([10, 100, 1000, 10000])
display(e)

f = np.array([1, np.e, np.e**2, np.e**3])
display(f)

g = np.array([0, np.pi/2, np.pi, 3*np.pi/2])
display(g)


h = np.array([1.1, 2.5, 3.7, 4.6, 5.9])
display(h)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

array([[ 0,  1,  4],
       [ 9, 16, 25],
       [36, 49, 64]])

array([-1, -2,  3,  4])

array([ 1,  4,  9, 16])

array([   10,   100,  1000, 10000])

array([ 1.        ,  2.71828183,  7.3890561 , 20.08553692])

array([0.        , 1.57079633, 3.14159265, 4.71238898])

array([1.1, 2.5, 3.7, 4.6, 5.9])

In [3]:
# 1.numpy.add:

display(np.add(a, b))

array([[ 0,  2,  6],
       [12, 20, 30],
       [42, 56, 72]])

In [4]:
# 2.numpy.subtract:

display(np.subtract(a, b))

array([[  0,   0,  -2],
       [ -6, -12, -20],
       [-30, -42, -56]])

In [5]:
# 3.numpy.multiply:

display(np.multiply(a, b))

array([[  0,   1,   8],
       [ 27,  64, 125],
       [216, 343, 512]])

In [6]:
# 4.numpy.divide:

display(np.divide(a, b))

/tmp/ipykernel_11804/3453180742.py:3: RuntimeWarning: invalid value encountered in true_divide
  display(np.divide(a, b))


array([[       nan, 1.        , 0.5       ],
       [0.33333333, 0.25      , 0.2       ],
       [0.16666667, 0.14285714, 0.125     ]])

In [7]:
# 5.numpy.floor_divide:

display(np.floor_divide(a, b))

/tmp/ipykernel_11804/340940192.py:3: RuntimeWarning: divide by zero encountered in floor_divide
  display(np.floor_divide(a, b))


array([[0, 1, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [8]:
# 6.numpy.power:

display(np.power(a, b))

array([[                   1,                    1,                   16],
       [               19683,           4294967296,   298023223876953125],
       [-5108087961858080768,  6812400838176574343,                    0]])

In [9]:
# 7.numpy.mod:

display(np.mod(a, b))

/tmp/ipykernel_11804/3303606514.py:3: RuntimeWarning: divide by zero encountered in remainder
  display(np.mod(a, b))


array([[0, 0, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [10]:
# 8.numpy.remainder:

display(np.remainder(a, b))

/tmp/ipykernel_11804/3649448712.py:3: RuntimeWarning: divide by zero encountered in remainder
  display(np.remainder(a, b))


array([[0, 0, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [11]:
# 9.numpy.fmod:

display(np.fmod(a, b))

/tmp/ipykernel_11804/2130210054.py:3: RuntimeWarning: divide by zero encountered in fmod
  display(np.fmod(a, b))


array([[0, 0, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [14]:
# 10.numpy.abs:

display(np.abs(c))

array([1, 2, 3, 4])

In [15]:
# 11.numpy.sqrt:

display(np.sqrt(d))

array([1., 2., 3., 4.])

In [16]:
# 12.numpy.exp:

display(np.exp(d))

array([2.71828183e+00, 5.45981500e+01, 8.10308393e+03, 8.88611052e+06])

In [21]:
# 13.numpy.log:

display(np.log(f))

/tmp/ipykernel_11804/4143458945.py:3: RuntimeWarning: divide by zero encountered in log
  display(np.log(f))


array([      -inf, 0.45158271, 1.14472989, 1.55019499])

In [20]:
# 14.numpy.log10:

display(np.log10(e))

array([0.        , 0.43429448, 0.86858896, 1.30288345])

In [24]:
# 15.numpy.sin:

display(np.sin(g))

array([ 0.0000000e+00,  1.0000000e+00,  1.2246468e-16, -1.0000000e+00])

In [25]:
# 16.numpy.cos:

display(np.cos(g))

array([ 1.0000000e+00,  6.1232340e-17, -1.0000000e+00, -1.8369702e-16])

In [26]:
# 17.numpy.tan:

display(np.tan(g))

array([ 0.00000000e+00,  1.63312394e+16, -1.22464680e-16,  5.44374645e+15])

In [30]:
# 18.numpy.ceil:

display(np.ceil(h))

array([2., 3., 4., 5., 6.])

In [31]:
# 19.numpy.floor:

display(np.floor(h))

array([1., 2., 3., 4., 5.])

In [32]:
# 20.numpy.maximum:

display(np.maximum(a,b))

array([[ 0,  1,  4],
       [ 9, 16, 25],
       [36, 49, 64]])

In [ ]:
# 21.numpy.mammum:

display(np.maximum(a,b))